/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To evaluate the scale and volume of data distribution by customer, product, and region.

SQL Functions Used:
    - COUNT(), SUM(), AVG()
    - GROUP BY, ORDER BY

Tables Used:
    - gold.dim_customers
    - gold.dim_products
    - gold.fact_sales
===============================================================================
*/

SELECT * FROM gold.dim_customers 
SELECT * FROM gold.dim_products
SELECT * FROM gold.fact_Sales

-- Find total number customers by countries
SELECT 
	country, 
	COUNT(customer_key) As total_customers 
FROM gold.dim_customers 
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT 
	gender, 
	COUNT(customer_key) As total_customers 
FROM gold.dim_customers 
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT 
	category, 
	COUNT(product_key) As total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category?
SELECT 
	category, 
	AVG(cost) As average_cost 
FROM gold.dim_products 
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	pr.category, 
	SUM(s.sales_amount) As total_revenue 
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products As pr
ON s.product_key = pr.product_key
GROUP BY pr.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
SELECT 
	cu.customer_key, 
	cu.first_name,
	cu.last_name,
	SUM(s.sales_amount) As total_revenue 
FROM gold.fact_sales AS s 
LEFT JOIN gold.dim_customers As cu
ON s.customer_key = cu.customer_key
GROUP BY cu.customer_key, cu.first_name, cu.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
	cu.country, 
	SUM(s.quantity) AS sold_items 
FROM gold.fact_sales AS s 
LEFT JOIN gold.dim_customers As cu
ON s.customer_key = cu.customer_key
GROUP BY cu.country
ORDER BY sold_items DESC
